name: Node.js Package

on:
  push:
    branches:
      - release

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: martinbeentjes/npm-get-version-action@v1.3.1
        id: get-npm-version

  build-and-publish:
    needs: get-version
    runs-on: ubuntu-latest
    steps:
      - run: "echo NPM Version: ${{ steps.npm-version.outputs.current-version }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
      - run: npm install # use npm install instead of npm ci to generate package-lock.json if it doesn't exist.
      - run: echo "No tests specified" # replace this with your test command if you have tests.
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  create-release:
    needs: get-version
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.npm-version.outputs.current-version }}.${{ github.run_number }}
          release_name: Release v${{ steps.npm-version.outputs.current-version }}
          draft: false
          prerelease: false
