name: Node.js Package

on:
  push:
    branches:
      - release

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest version
        id: version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Git
        run: |
          echo Branch name is: ${{ github.ref_name }}
          echo Short sha: ${{ steps.git.outputs.short_sha}}
          echo Version is: ${{ steps.version.outputs.current-version}}

  build-and-publish:
    needs: get-version
    runs-on: ubuntu-latest
    steps:
      - run: "echo NPM Version: ${{ steps.npm-version.outputs.current-version }}"
