name: Node.js Package

on:
  push:
    branches:
      - release

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: martinbeentjes/npm-get-version-action@v1.3.1
        id: get-npm-version

  build-and-publish:
    needs: get-version
    runs-on: ubuntu-latest
    steps:
      - run: "echo NPM Version: ${{ steps.npm-version.outputs.current-version }}"
